[versions]

activity-compose = "1.8.2"
android-gradle-plugin = "8.13.2"
compose-bom = "2024.04.00"
camera = "1.3.1"
core-ktx = "1.12.0"
esp-idf-provisioning = "lib-2.4.3"
eventbus = "3.3.1"
gson = "2.10.1"
kotlin = "1.9.23"
ksp = "1.9.23-1.0.19"
lifecycle = "2.7.0"
material = "1.11.0"
material-icons = "1.6.3"
mlkit-barcode-scanning = "17.2.0"
navigation-compose = "2.7.7"
room = "2.6.1"

[libraries]

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

camera-core = { module = "androidx.camera:camera-core", version.ref = "camera" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camera" }

material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons"}
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

mlkit-barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "mlkit-barcode-scanning" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
esp-idf-provisioning = { module = "com.github.espressif:esp-idf-provisioning-android", version.ref = "esp-idf-provisioning" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
